#!/bin/bash
function usage() {
  echo -e "Usage:\n  $0 salt://path/to/template.j2 listofhosts\n\n"
}
if [ ${#@} -lt 2 ] ; then
  usage
  exit 1
fi
TEMPLATE="${1:?Please pass a template name as the first argument}"
# TEMPLATE="${TEMPLATE:=salt://profile/obs-keepalived/files/etc/keepalived/keepalived.conf.j2}"
shift
for hostname in $* ; do
    echo "Clear all other caches and update data on minion $hostname ... output following:"
    salt "$hostname" saltutil.refresh_pillar
    salt "$hostname" state.apply profile-base.sync-salt-information
    echo "Rendering template on minion $hostname:"
    salt "$hostname" template.render "$TEMPLATE"
done
